# Generated by Django 4.2 on 2024-08-17 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        auto_created=True,
                        max_length=100,
                        unique=True,
                        verbose_name="slug",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="create date"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="update date"),
                ),
            ],
            options={
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.CreateModel(
            name="Shoe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        default="Male",
                        max_length=6,
                        verbose_name="gender",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="name")),
                ("description", models.TextField(verbose_name="description")),
                ("stock", models.PositiveIntegerField(verbose_name="stock")),
                (
                    "rate",
                    models.PositiveSmallIntegerField(default=0, verbose_name="rate"),
                ),
                (
                    "free_shipping",
                    models.BooleanField(default=False, verbose_name="free shipping"),
                ),
                (
                    "image",
                    models.ImageField(upload_to="shoes/images", verbose_name="image"),
                ),
                ("price", models.PositiveIntegerField(default=0, verbose_name="price")),
                (
                    "create_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="create date"),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="update date"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        to="shoes.category", verbose_name="categories"
                    ),
                ),
            ],
            options={
                "verbose_name": "shoe",
                "verbose_name_plural": "shoes",
            },
        ),
    ]
