# Generated by Django 4.2 on 2024-08-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shoes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shoe",
            name="gender",
            field=models.CharField(
                choices=[("Men", "Men"), ("Women", "Women")],
                default="Men",
                max_length=6,
                verbose_name="gender",
            ),
        ),
    ]
